"""Create user table

Revision ID: 358e3d9c1d4a
Revises: 
Create Date: 2024-11-19 19:49:40.583644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '358e3d9c1d4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('emergency_contact', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.drop_table('rides')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('emergency_contact', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('phone_number', name='users_phone_number_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('rides',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('origin', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('destination', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ride_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('driver_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('car_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estimated_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fare_estimate', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('ride_status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='rides_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rides_pkey')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
